        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 07 17:56:42 2022
        MODULE KPAMES__genmod
          INTERFACE 
            SUBROUTINE KPAMES(KPAC,MESSC)
              INTEGER(KIND=4) :: KPAC
              INTEGER(KIND=4) :: MESSC
            END SUBROUTINE KPAMES
          END INTERFACE 
        END MODULE KPAMES__genmod
